namespace SpriteKind {
    export const gigameal = SpriteKind.create()
    export const protection = SpriteKind.create()
    export const gg = SpriteKind.create()
}
scene.onHitWall(SpriteKind.Player, function (sprite, location) {
    toxic.setImage(img`
        ....................
        ...999..............
        ...92229............
        ...9222.............
        ...92..9............
        .....999............
        ...99...............
        ...999.99999........
        .99999.9999.........
        ....................
        .9..................
        .99..........999....
        ..99...99.99.9......
        ..9.99...99999......
        .............999....
        99.9...9............
        ......9..99.........
        ......9.99..........
        ....................
        ....................
        `)
    tiles.placeOnRandomTile(toxic, sprites.dungeon.purpleOuterSouth1)
    scene.cameraShake(7, 500)
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.saplingPine, function (sprite, location) {
    info.changeScoreBy(6)
    toxic = sprites.create(img`
        ....................
        ...999..............
        ...99999............
        ...992999...........
        ...999999...........
        ...99999............
        ...99...............
        ...999999999........
        .9999999999.........
        .9..................
        .9..................
        .99..........999....
        ..9999999999.9......
        ..999999999999......
        ...9...9..9..999....
        9999..99..9.........
        ..9...9..99.........
        ..9..99.99..........
        ....................
        ....................
        `, SpriteKind.Player)
})
info.onScore(7, function () {
    game.gameOver(true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.gigameal, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    toxic = sprites.create(img`
        ....................
        ...999..............
        ...99999............
        ...992999...........
        ...999999...........
        ...99999............
        ...99...............
        ...999999999........
        .9999999999.........
        .9..................
        .9..................
        .99..........999....
        ..9999999999.9......
        ..999999999999......
        ...9...9..9..999....
        9999..99..9.........
        ..9...9..99.........
        ..9..99.99..........
        ....................
        ....................
        `, SpriteKind.gg)
    sprites.destroy(otherSprite)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    sprites.destroy(otherSprite)
    info.changeLifeBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeScoreBy(-1)
    sprites.destroy(otherSprite)
    info.changeLifeBy(-1)
})
let kaiju: Sprite = null
let Mega_meast: Sprite = null
let toxic: Sprite = null
toxic = sprites.create(img`
    ....................
    ...999..............
    ...99999............
    ...992999...........
    ...999999...........
    ...99999............
    ...99...............
    ...999999999........
    .9999999999.........
    .9..................
    .9..................
    .99..........999....
    ..9999999999.9......
    ..999999999999......
    ...9...9..9..999....
    9999..99..9.........
    ..9...9..99.........
    ..9..99.99..........
    ....................
    ....................
    `, SpriteKind.Player)
music.play(music.stringPlayable("E B C5 A B G A F ", 265), music.PlaybackMode.LoopingInBackground)
tiles.setCurrentTilemap(tilemap`level2`)
controller.moveSprite(toxic)
scene.cameraFollowSprite(toxic)
tiles.placeOnRandomTile(toxic, sprites.builtin.oceanDepths4)
info.setScore(0)
info.setLife(3)
game.onUpdateInterval(2000, function () {
    Mega_meast = sprites.create(img`
        . . . . . . . 6 . . . . . . . . 
        . . . . . . 8 6 6 . . . 6 8 . . 
        . . . e e e 8 8 6 6 . 6 7 8 . . 
        . . e 2 2 2 2 e 8 6 6 7 6 . . . 
        . e 2 2 4 4 2 7 7 7 7 7 8 6 . . 
        . e 2 4 4 2 6 7 7 7 6 7 6 8 8 . 
        e 2 4 5 2 2 6 7 7 6 2 7 7 6 . . 
        e 2 4 4 2 2 6 7 6 2 2 6 7 7 6 . 
        e 2 4 2 2 2 6 6 2 2 2 e 7 7 6 . 
        e 2 4 2 2 4 2 2 2 4 2 2 e 7 6 . 
        e 2 4 2 2 2 2 2 2 2 2 2 e c 6 . 
        e 2 2 2 2 2 2 2 4 e 2 e e c . . 
        e e 2 e 2 2 4 2 2 e e e c . . . 
        e e e e 2 e 2 2 e e e c . . . . 
        e e e 2 e e c e c c c . . . . . 
        . c c c c c c c . . . . . . . . 
        `, SpriteKind.Food)
    tiles.placeOnRandomTile(Mega_meast, sprites.dungeon.purpleOuterSouth1)
    toxic.setImage(img`
        ....................
        ...999..............
        ...99999............
        ...992999...........
        ...999999...........
        ...99999............
        ...99...............
        ...999999999........
        .9999999999.........
        .9..................
        .9..................
        .99..........999....
        ..9999999999.9......
        ..999999999999......
        ...9...9..9..999....
        9999..99..9.........
        ..9...9..99.........
        ..9..99.99..........
        ....................
        ....................
        `)
})
game.onUpdateInterval(1000, function () {
    kaiju = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e 2 . . . . . . . . 
        . . . . . e 2 e . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . e . . 
        . . . . e e e e e e e e e e . . 
        . . . . e e e e e e . . . . . . 
        `, SpriteKind.Enemy)
    tiles.placeOnRandomTile(kaiju, assets.tile`myTile`)
    kaiju.follow(toxic, 78)
})
game.onUpdateInterval(1000, function () {
    kaiju = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e 2 . . . . . . . . 
        . . . . . e 2 e . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . e . . 
        . . . . e e e e e e e e e e . . 
        . . . . e e e e e e . . . . . . 
        `, SpriteKind.Enemy)
    tiles.placeOnRandomTile(kaiju, sprites.dungeon.hazardLava0)
    kaiju.follow(toxic, 123)
})
game.onUpdateInterval(1000, function () {
    kaiju = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e 2 . . . . . . . . 
        . . . . . e 2 e . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . e . . 
        . . . . e e e e e e e e e e . . 
        . . . . e e e e e e . . . . . . 
        `, SpriteKind.Enemy)
    tiles.placeOnRandomTile(kaiju, sprites.dungeon.collectibleRedCrystal)
    kaiju.follow(toxic, 123)
})
game.onUpdateInterval(1000, function () {
    kaiju = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e 2 . . . . . . . . 
        . . . . . e 2 e . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . e . . 
        . . . . e e e e e e e e e e . . 
        . . . . e e e e e e . . . . . . 
        `, SpriteKind.Enemy)
    tiles.placeOnRandomTile(kaiju, sprites.builtin.oceanDepths4)
    kaiju.follow(toxic, 77)
})
game.onUpdateInterval(1000, function () {
    kaiju = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e 2 . . . . . . . . 
        . . . . . e 2 e . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . e . . 
        . . . . e e e e e e e e e e . . 
        . . . . e e e e e e . . . . . . 
        `, SpriteKind.Enemy)
    tiles.placeOnRandomTile(kaiju, sprites.dungeon.greenOuterNorthWest)
    kaiju.follow(toxic, 88)
})
game.onUpdateInterval(1000, function () {
    kaiju = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e 2 . . . . . . . . 
        . . . . . e 2 e . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . e . . 
        . . . . e e e e e e e e e e . . 
        . . . . e e e e e e . . . . . . 
        `, SpriteKind.Enemy)
    tiles.placeOnRandomTile(kaiju, sprites.dungeon.purpleOuterSouth1)
    kaiju.follow(toxic, 77)
})
game.onUpdateInterval(1000, function () {
    kaiju = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e 2 . . . . . . . . 
        . . . . . e 2 e . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . e . . 
        . . . . e e e e e e e e e e . . 
        . . . . e e e e e e . . . . . . 
        `, SpriteKind.Enemy)
    tiles.placeOnRandomTile(kaiju, sprites.builtin.forestTiles0)
    kaiju.follow(toxic, 56)
})
game.onUpdateInterval(1000, function () {
    kaiju = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e 2 . . . . . . . . 
        . . . . . e 2 e . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . e . . 
        . . . . e e e e e e e e e e . . 
        . . . . e e e e e e . . . . . . 
        `, SpriteKind.Enemy)
    tiles.placeOnRandomTile(kaiju, assets.tile`myTile`)
    kaiju.follow(toxic, 22)
})
game.onUpdateInterval(1000, function () {
    kaiju = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e 2 . . . . . . . . 
        . . . . . e 2 e . . . . . . . . 
        . . . . e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . e e e e e e . . . . . . . . 
        . . . . . e e e . . . . . . . . 
        . . . . . e e e . . . . . e . . 
        . . . . e e e e e e e e e e . . 
        . . . . e e e e e e . . . . . . 
        `, SpriteKind.Enemy)
    tiles.placeOnRandomTile(kaiju, sprites.dungeon.chestClosed)
    kaiju.follow(toxic, 55)
})
game.onUpdateInterval(200, function () {
    Mega_meast = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ........4eee........
        .......eeeeee.......
        .........cc.........
        .........4c.........
        ........4444........
        .......444444.......
        ......44444444......
        .....4444444444.....
        .....eeeeeeeeee.....
        .....eeeeeeeecc.....
        ......eeeeeecc......
        .......eccccc.......
        ....................
        ....................
        `, SpriteKind.gigameal)
    tiles.placeOnRandomTile(Mega_meast, sprites.castle.tilePath6)
})
